### ISSUE TITLE
openalpr as docker container

### ISSUE THREAD

**Issue by FadelChafai** [openalpr/openalpr#950]
Hi

Is  there a way to run openalpr as a container an instead of using

docker run -it --rm -v $(pwd):/data:ro openalpr -c eu h786poj.jpg

we can use for ex : container-ip -c eu h786poj.jpg

Thank you

**Comment by gulbalee** [comment]
Theres an http wrapper image from sclaflin. Try this docker-compose.yaml, and then from the host machine browser, enter the ip of the host or open-alpr-http-wrapper container with port 3000, for example 172.18.0.2:3000 or host IP 192.168.X.X:3000. 

<img width="540" alt="Screenshot 2022-02-16 at 2 11 22 AM" src="https://user-images.githubusercontent.com/11457775/154150017-ee39c83b-ece1-4d2b-93af-b0f3aa91261b.png">


```
version: "3.9"
services:
 open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
    ports:
      - 3000:3000
```
